"""
app.py -- OmniBrain E.R.I.S. Command Center
Integrates Core (Attachments), Advanced (Roles), and Elite (Export) Hackathon Bounties.
"""
import streamlit as st
import os
import datetime
import json
import re
import time
from google import genai
from youtube_transcript_api import YouTubeTranscriptApi
from pypdf import PdfReader
import trafilatura

import agent_core as ac

# --- PERMANENT FIX: Force-disable Vertex AI routing ---
# This ensures your API key is always directed to the correct Gemini API endpoint
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "false"

STORAGE_FILE = "brain_storage.json"
ATTACHMENT_DIR = "attachments"

os.makedirs(ATTACHMENT_DIR, exist_ok=True)

def load_persisted_memories():
    if os.path.exists(STORAGE_FILE):
        try:
            with open(STORAGE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception: return []
    return []

def save_persisted_memories(memories):
    try:
        with open(STORAGE_FILE, "w", encoding="utf-8") as f:
            json.dump(memories, f, indent=4, default=str)
    except Exception as e: st.error(f"Storage Error: {e}")

@st.cache_data(show_spinner=False)
def parse_pdf_cached(uploaded_file):
    reader = PdfReader(uploaded_file)
    return "\n".join(page.extract_text() for page in reader.pages if page.extract_text())

st.set_page_config(page_title="OmniBrain E.R.I.S.", page_icon="🌍", layout="wide")
st.markdown("""
    <style>
        .block-container { max-width: 1200px; padding-top: 2rem; }
        #MainMenu {visibility: hidden;} footer {visibility: hidden;}
        .stMetric { background: #161b22; padding: 15px; border-radius: 10px; border: 1px solid #30363d; }
    </style>
""", unsafe_allow_html=True)

st.title("OmniBrain E.R.I.S. 🌍")
st.caption("Environmental Report Intelligence System | Command & Control Center")

# --- BULLETPROOF GEMINI AUTHENTICATION ---
API_KEY = st.secrets.get("GEMINI_API_KEY") or os.environ.get("GEMINI_API_KEY")
if not API_KEY:
    st.error("🚨 No GEMINI_API_KEY found in .streamlit/secrets.toml or environment variables.")
    st.stop()

# Strip any accidental whitespace
API_KEY = API_KEY.strip()
client = genai.Client(api_key=API_KEY)
FALLBACK_MODELS = ["gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.6-flash"]

def safe_generate(contents):
    import json
    
    # 1. Try all fallback models sequentially
    for model_id in FALLBACK_MODELS:
        try:
            if not client: raise Exception("No API Key configured.")
            return client.models.generate_content(model=model_id, contents=contents)
        except Exception:
            # Silently catch timeouts, 429s, 401s, and network drops, then try next model
            continue
            
    # 2. UNIVERSAL FAILSAFE: If all models fail, trigger the static offline override
    class MockResponse:
        def __init__(self, text):
            self.text = text
            
    prompt_str = str(contents)
    snippet = prompt_str[:50].replace('\n', ' ').strip()
    
    # Format perfectly safe JSON dictionaries and dump them to strings
    if "Finalizer Agent" in prompt_str:
        return MockResponse(f"## 🌍 [SYSTEM DEGRADED - STATIC PROTOCOL ENGAGED]\n\n*Live LLM routing failed. Executing static offline holding pattern for target data: `{snippet}...`*\n\n1. **Immediate Hold:** Secure the reported perimeter until live connection is re-established.\n2. **Manual Escalation:** Forward incident details to human oversight committee immediately.")
        
    elif "Planning Agent" in prompt_str:
        plan_dict = {
            "goal": f"[STATIC OVERRIDE] Maintain perimeter for: {snippet}", 
            "tasks": ["Deploy Static Defense", "Wait for Network Restoration"], 
            "evidence": {"Deploy Static Defense": ["Offline Protocol Triggered"]}, 
            "missing": []
        }
        return MockResponse(json.dumps(plan_dict))
        
    elif "Critic Agent" in prompt_str:
        critic_dict = {
            "issues": ["Network offline. Plan generated by static failsafe."], 
            "improvement": "Restore API connection."
        }
        return MockResponse(json.dumps(critic_dict))
        
    elif "Perception Agent" in prompt_str:
        perception_dict = {
            "found": True, 
            "items": [{"description": "[OFFLINE] Manual check required", "date": "2026-08-08"}]
        }
        return MockResponse(json.dumps(perception_dict))
        
    else:
        # Default to Ingestion Metadata Schema
        ingest_dict = {
            "summary": f"[STATIC OVERRIDE] Network/API unreachable. Fallback active for: {snippet}...",
            "concepts": ["Offline Mode", "Manual Review Required"],
            "status": "Unknown",
            "recommendations": "System degraded. Escalate to manual human review.",
            "notes": "Automated processing suspended."
        }
        return MockResponse(json.dumps(ingest_dict))

ac.configure(safe_generate)

# --- STATE & EVENT INIT ---
if "memories" not in st.session_state: st.session_state.memories = load_persisted_memories()
if "pending_proposal" not in st.session_state: st.session_state.pending_proposal = None
if "last_roadmap" not in st.session_state: st.session_state.last_roadmap = None

if "events_registered" not in st.session_state:
    def _handle_memory_added(new_memory: dict):
        items = ac.perception_scan(new_memory)
        if items: st.session_state.pending_proposal = items
    ac.on(ac.MemoryEvent.ADDED, _handle_memory_added)
    st.session_state.events_registered = True

# --- ADVANCED BOUNTY: ROLE-AWARE FILTERS ---
with st.sidebar:
    st.header("🔐 Security Clearance")
    # 6 Explicit Roles from the Bounty
    ALL_ROLES = ["User", "Admin", "Authority", "Hospital", "Investigator", "Reviewer"]
    
    current_role = st.selectbox("Current Role Override", ALL_ROLES)
    st.divider()

    st.header("📥 Ingest Incident Report")
    source_type = st.selectbox("Data Source", ["Text Paste", "PDF Document", "YouTube Video", "Website URL"])
    title = st.text_input("Incident Designation")
    
    # FIX: Upgrade to multiselect so a report can belong to multiple departments
    report_role = st.multiselect("Visibility Scope", ["All"] + ALL_ROLES, default=["All"])
    memory_date = st.date_input("Date Logged", datetime.date.today())
    
    # --- CORE BOUNTY: ATTACHMENTS ---
    evidence_file = st.file_uploader("Attach Field Evidence (Image/Doc)")
    
    content_text = ""
    if source_type == "Text Paste": content_text = st.text_area("Paste report details...")
    elif source_type == "PDF Document":
        pdf_file = st.file_uploader("Upload PDF Report", type=["pdf"])
        if pdf_file: content_text = parse_pdf_cached(pdf_file)
    elif source_type == "YouTube Video":
        yt_url = st.text_input("YouTube Drone/Site Footage URL")
        if yt_url:
            try:
                video_id = yt_url.split("/")[-1].split("?")[0] if "youtu.be" in yt_url else yt_url.split("v=")[-1].split("&")[0]
                fetched = YouTubeTranscriptApi().fetch(video_id) if hasattr(YouTubeTranscriptApi(), 'fetch') else YouTubeTranscriptApi.get_transcript(video_id)
                
                formatted_transcript = []
                for t in fetched:
                    text_val = t.get('text', '') if isinstance(t, dict) else getattr(t, 'text', str(t))
                    start_val = t.get('start', 0) if isinstance(t, dict) else getattr(t, 'start', 0)
                    formatted_transcript.append(f"[{int(start_val)//60:02d}:{int(start_val)%60:02d}] {text_val}")
                
                content_text = "\n".join(formatted_transcript)
            except Exception as e: 
                st.error("Transcript extraction failed.")

    if st.button("EXECUTE LOGGING PROTOCOL", use_container_width=True) and content_text and title:
        with st.spinner("Agent auditing report & extracting metadata..."):
            
            # Save Attachment Core Bounty
            attachment_path = None
            if evidence_file:
                attachment_path = os.path.join(ATTACHMENT_DIR, evidence_file.name)
                with open(attachment_path, "wb") as f: f.write(evidence_file.getbuffer())

            # Elite Bounty Schema Extractor
            save_prompt = f"""Analyze this environmental report and extract metadata as JSON only:
{{"summary": "2-3 sentence summary", "concepts": ["hazard", "compliance"], "status": "Critical/Moderate/Resolved", "recommendations": "Actionable steps", "notes": "Extra context"}}
Content:\n{content_text[:10000]}"""
            try:
                parsed = ac.safe_json_parse(safe_generate(save_prompt).text)
                new_memory = {
                    "title": title, "type": source_type, "date": str(memory_date), "role_scope": report_role,
                    "summary": parsed.get("summary", ""), "concepts": parsed.get("concepts", []),
                    "status": parsed.get("status", "Unknown"), "recommendations": parsed.get("recommendations", ""),
                    "notes": parsed.get("notes", ""), "attachment": attachment_path, "raw": content_text
                }
                st.session_state.memories.append(new_memory)
                save_persisted_memories(st.session_state.memories)
                ac.emit(ac.MemoryEvent.ADDED, new_memory)
                st.success(f"Dossier Secured: {title}")
                st.rerun()
            except Exception as e: st.warning(f"⚠️ {e}")

# --- GOVERNANCE GATE (Agentic) ---
if st.session_state.pending_proposal:
    with st.container(border=True):
        st.warning("⚠️ Perception Agent detected urgent compliance deadlines in recent report!")
        for item in st.session_state.pending_proposal:
            st.write(f"- {item.get('description')} — **{item.get('date')}**")
        c1, c2 = st.columns(2)
        if c1.button("Approve Deadline Lock"):
            st.session_state.pending_proposal = None
            st.rerun()
        if c2.button("Dismiss"):
            st.session_state.pending_proposal = None
            st.rerun()

# --- FILTER VISIBLE MEMORIES ---
visible_memories = []
for m in st.session_state.memories:
    scope = m.get("role_scope", ["All"])
    if isinstance(scope, str): scope = [scope]
    if "All" in scope or current_role in scope:
        visible_memories.append(m)

# --- CRISIS COMMAND CENTER METRICS RIBBON ---
col1, col2, col3, col4 = st.columns(4)
total_reps = len(st.session_state.memories)
visible_count = len(visible_memories)
critical_count = sum(1 for m in visible_memories if "Critical" in m.get("status", ""))

col1.metric("🔒 Clearance Level", current_role)
col2.metric("📁 Scoped Reports", visible_count, f"of {total_reps} total")
col3.metric("🚨 Critical Hazards", critical_count, delta_color="inverse")
col4.metric("🛡️ Agent Status", "Active / Resilient")

st.divider()

# --- ROADMAP WORKFLOW ---
st.subheader("⚡ Autonomous Remediation Command Center")
if st.button("🚀 Initialize Multi-Agent Audit & Roadmap", use_container_width=True):
    if not visible_memories: 
        st.warning("⚠️ Access Denied: No reports available for your security clearance.")
    else:
        # High-speed telemetry animation
        prog = st.progress(0, text="Initializing Agent Mesh...")
        time.sleep(0.2)
        prog.progress(25, text="Executing Scoped Semantic Retrieval...")
        time.sleep(0.2)
        prog.progress(50, text="Synthesizing Planner Matrix...")
        time.sleep(0.2)
        prog.progress(75, text="Running Critic Hallucination Guardrails...")
        time.sleep(0.2)
        try:
            st.session_state.last_roadmap = ac.generate_roadmap(visible_memories, window_days=7)
            prog.progress(100, text="✅ Autonomous Audit Complete.")
            time.sleep(0.3)
            prog.empty()
        except Exception as e: 
            prog.empty()
            st.error(f"Planning failed: {e}")

if st.session_state.last_roadmap:
    result = st.session_state.last_roadmap
    
    # Command Center Tabs for Clean UI
    tab_roadmap, tab_trace, tab_critic = st.tabs(["🌍 Final Directive", "🔍 Explainable Trace", "🧠 Critic & Evidence Audit"])
    
    with tab_roadmap:
        st.markdown("### Approved Emergency Remediation Protocol")
        st.markdown(result["final"])
        
        if "evidence" in result["plan"]:
            st.markdown("#### 🔗 Mandated Task-to-Evidence Links")
            for task, sources in result["plan"]["evidence"].items():
                st.info(f"**{task}**\n*Verified Source Report(s):* `{', '.join(sources)}`")

    with tab_trace:
        st.markdown("### Semantic Retrieval Telemetry")
        for m in result.get("retrieval_trace", []):
            st.markdown(f"> **{m['title']}**\n> *Telemetry Reason:* `{m['_reason']}`")
    
    with tab_critic:
        st.markdown("### Critic Hallucination Defense Grid")
        conf = result["critic"]["confidence"]
        st.metric("Confidence Score", conf['level'])
        st.write(f"**Audit Notes:** {conf['reason']}")
        with st.expander("View Raw Planner JSON"):
            st.json(result["plan"])

st.divider()

# --- ELITE & CORE BOUNTIES: COMMAND DATABASE ---
st.subheader("📂 Verified Incident Database & Evidence Vault")
if visible_memories:
    for i, d in enumerate(visible_memories):
        status_color = "🔴" if "Critical" in d.get('status','') else "🟢"
        with st.expander(f"{status_color} [{d.get('status', 'N/A').upper()}] {d['title']} — (Logged: {d['date']})"):
            
            mc1, mc2 = st.columns([2, 1])
            with mc1:
                st.markdown(f"**Security Scope:** `{', '.join(d.get('role_scope', ['All']))}`")
                st.markdown(f"**Executive Summary:** {d['summary']}")
                st.markdown(f"**Recommended Action:** {d.get('recommendations', 'None')}")
            with mc2:
                st.markdown(f"**Tags / Concepts:**")
                st.code(", ".join(d.get('concepts', [])))

            # CORE BOUNTY: Attachment Display
            if d.get("attachment") and os.path.exists(d["attachment"]):
                st.markdown("---")
                st.markdown("**📎 Attached Field Evidence:**")
                if d["attachment"].lower().endswith(('.png', '.jpg', '.jpeg')):
                    try:
                        st.image(d["attachment"], width=350)
                    except Exception:
                        st.warning("⚠️ Attachment preview unavailable.")
                else:
                    st.code(d["attachment"])
            
            st.markdown("---")
            # ELITE BOUNTY: Project-Specific Report Export
            safe_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', d['title'])
            html_report = f"""
            <html><body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0e1117; color: #c9d1d9; padding: 40px; max-width: 800px; margin: auto;">
            <div style="border-left: 4px solid {'#ff4b4b' if 'Critical' in d.get('status','') else '#00cc66'}; padding-left: 20px;">
                <h1 style="color: #ffffff; margin-bottom: 5px;">E.R.I.S. Incident Report</h1>
                <h3 style="color: #8b949e; margin-top: 0;">{d['title']}</h3>
            </div>
            <hr style="border: 1px solid #30363d; margin: 20px 0;">
            <p><b>Date Logged:</b> {d['date']}</p>
            <p><b>Severity Status:</b> <span style="color: {'#ff4b4b' if 'Critical' in d.get('status','') else '#00cc66'}; font-weight: bold;">{d.get('status', 'N/A')}</span></p>
            <p><b>Security Scope:</b> {', '.join(d.get('role_scope', ['All']))}</p>
            
            <h3 style="color: #58a6ff;">Executive Summary</h3>
            <p style="background: #161b22; padding: 15px; border-radius: 6px; border: 1px solid #30363d;">{d['summary']}</p>
            
            <h3 style="color: #58a6ff;">Mandated Remediation Protocol</h3>
            <p style="background: #161b22; padding: 15px; border-radius: 6px; border: 1px solid #30363d;">{d.get('recommendations', 'N/A')}</p>
            
            <h3 style="color: #58a6ff;">Field Notes & Telemetry</h3>
            <p style="background: #161b22; padding: 15px; border-radius: 6px; border: 1px solid #30363d;">{d.get('notes', 'N/A')}</p>
            
            <hr style="border: 1px solid #30363d; margin: 20px 0;">
            <p style="font-size: 0.85em; color: #8b949e; text-align: center;"><i>Generated autonomously by OmniBrain E.R.I.S. (Environmental Report Intelligence System)</i></p>
            </body></html>
            """
            st.download_button(
                label="📥 Export Certified Incident Dossier (HTML)",
                data=html_report,
                file_name=f"ERIS_Dossier_{safe_title}.html",
                mime="text/html",
                key=f"dl_{safe_title}_{i}"
            )
else:
    st.info("No incident reports accessible for your current security clearance role.")